-- SYS 관리자 계정
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- 사용자 계정 생성
CREATE USER mProject_lsh IDENTIFIED BY mproject1234;

--생성한 사용자계정에 권한 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO mProject_lsh;

-- 테이블 스페이스 할당
ALTER USER mProject_lsh DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-------------------------------------------------------------------

CREATE TABLE "MEMBER" (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NM VARCHAR2(30) NOT NULL,
	ACCOUNT_NO VARCHAR2(30) DEFAULT '-',
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN ('Y','N'))
);

CREATE TABLE "ACCOUNT" (
	MEMBER_NO NUMBER REFERENCES "MEMBER"(MEMBER_NO),
	MEMBER_NAME VARCHAR(30) NOT NULL,
	ACCOUNT_NO VARCHAR2(30) NOT NULL,
	ACCOUNT_PW VARCHAR2(10) NOT NULL,
	BALANCE NUMBER DEFAULT 0,
	UNIQUE (ACCOUNT_NO)
);

SELECT * FROM "MEMBER";
SELECT * FROM "ACCOUNT";

COMMIT;

CREATE SEQUENCE 

-- 회원번호 시퀀스
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- 회원가입
INSERT INTO "MEMBER"
VALUES (SEQ_MEMBER_NO.NEXTVAL,?,?,?,DEFAULT,DEFAULT)

-- 로그인
SELECT MEMBER_NO,MEMBER_ID,MEMBER_NM,SECESSION_FL
FROM "MEMBER"
WHERE MEMBER_ID=?
AND MEMBER_PW=?
AND SECESSION='N';

-- 내 정보(계좌 조회)
SELECT a.ACCOUNT_NO, a.BALANCE
FROM "ACCOUNT" a
JOIN "MEMBER" USING (MEMBER_NO)
WHERE "MEMBER_ID"='user01'
AND SECESSION_FL='N';

-- 계좌 등록
INSERT INTO "ACCOUNT"
VALUES (MEMBER_NO,MEMBER_NM,ACCOUNT_NO,ACCOUNT_PW,DEFAULT)

-- 입금
UPDATE "ACCOUNT" SET
BALANCE=BALANCE+?
WHERE ACCOUNT_NO =?;





