-- SYS 관리자 계정
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- 사용자 계정 생성
CREATE USER mProject_lsh IDENTIFIED BY mproject1234;

--생성한 사용자계정에 권한 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO mProject_lsh;

-- 테이블 스페이스 할당
ALTER USER mProject_lsh DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-------------------------------------------------------------------

CREATE TABLE "MEMBER" (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NM VARCHAR2(30) NOT NULL,
	ACCOUNT_NO NUMBER NOT NULL,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN ('Y','N'))
);

CREATE TABLE "ACCOUNT" (
	MEMBER_NO NUMBER REFERENCES "MEMBER"(MEMBER_NO),
	MEMBER_NAME VARCHAR(30) NOT NULL,
	ACCOUNT_NO NUMBER NOT NULL,
	ACCOUNT_PW NUMBER NOT NULL,
	BALANCE NUMBER DEFAULT 0
	UNIQUE (ACCOUNT_NO)
);
